// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Hv2NBdTgxin81fujhG1TcOeAr9E3GSk',
    appId: '1:1020749863902:web:f356873eb78d80b68a5b4f',
    messagingSenderId: '1020749863902',
    projectId: 'event-mgmt-system-e69ad',
    authDomain: 'event-mgmt-system-e69ad.firebaseapp.com',
    storageBucket: 'event-mgmt-system-e69ad.firebasestorage.app',
    measurementId: 'G-VXZ41JHCJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdXSqbEIDotHwBGQJIFqwOdOD6daaqMLo',
    appId: '1:1020749863902:android:cd35c782175e64f68a5b4f',
    messagingSenderId: '1020749863902',
    projectId: 'event-mgmt-system-e69ad',
    storageBucket: 'event-mgmt-system-e69ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxJBCyT7NHhbEq6kCX1qcjGdFOzNWLvDs',
    appId: '1:1020749863902:ios:60b774024f4f0e738a5b4f',
    messagingSenderId: '1020749863902',
    projectId: 'event-mgmt-system-e69ad',
    storageBucket: 'event-mgmt-system-e69ad.firebasestorage.app',
    iosBundleId: 'com.example.campusEventMgmtSystem',
  );
}
